name: s_offstage
description: A Flutter package with advanced animated transitions (fade, scale, slide, rotation) for showing/hiding widgets using Offstage - a powerful alternative to Visibility.
issue_tracker: https://github.com/SoundSliced/s_offstage/issues
repository: https://github.com/SoundSliced/s_offstage
version: 2.1.0
homepage: https://github.com/SoundSliced/s_offstage

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  s_packages: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
