name: s_offstage
description: A Flutter package for smooth loading/content transitions and content hiding/reveal widgets.
issue_tracker: https://github.com/SoundSliced/s_offstage/issues
repository: https://github.com/SoundSliced/s_offstage
version: 1.0.1
homepage: https://github.com/SoundSliced/s_offstage

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  sizer: ^3.1.3
  ticker_free_circular_progress_indicator: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
